// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXPIDD6uU5QyZfqQukY_xdiJsAjBcpWf4',
    appId: '1:155271901402:web:3c46fbe84d1474485db5e3',
    messagingSenderId: '155271901402',
    projectId: 'final-project-cmd',
    authDomain: 'final-project-cmd.firebaseapp.com',
    storageBucket: 'final-project-cmd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-iIjlfs2ya9QLNCteYnXIaKcFSi55ho',
    appId: '1:155271901402:android:5e4cf73c773c11265db5e3',
    messagingSenderId: '155271901402',
    projectId: 'final-project-cmd',
    storageBucket: 'final-project-cmd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjPQdwbRm86Tj7t7Vo6YkvweTfN-Xj08',
    appId: '1:155271901402:ios:eefd67692f81769c5db5e3',
    messagingSenderId: '155271901402',
    projectId: 'final-project-cmd',
    storageBucket: 'final-project-cmd.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectCmd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjPQdwbRm86Tj7t7Vo6YkvweTfN-Xj08',
    appId: '1:155271901402:ios:eefd67692f81769c5db5e3',
    messagingSenderId: '155271901402',
    projectId: 'final-project-cmd',
    storageBucket: 'final-project-cmd.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectCmd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXPIDD6uU5QyZfqQukY_xdiJsAjBcpWf4',
    appId: '1:155271901402:web:3aa2110fbc2ded8e5db5e3',
    messagingSenderId: '155271901402',
    projectId: 'final-project-cmd',
    authDomain: 'final-project-cmd.firebaseapp.com',
    storageBucket: 'final-project-cmd.firebasestorage.app',
  );
}
